/** Kurze Aussagesätze (Modul 7, ohne Fragezeichen). */
export const SHORT_SENTENCES: readonly string[] = [
  'Die Sonne scheint.',
  'Ich lerne heute tippen.',
  'Das Wetter ist schön.',
  'Wir gehen in den Park.',
  'Der Hund schläft im Garten.',
  'Meine Finger finden die Tasten.',
  'Der Kaffee ist noch warm.',
  'Heute ist ein guter Tag.',
  'Sie liest ein spannendes Buch.',
  'Das Fenster steht offen.',
  'Wir trinken am Abend Tee.',
  'Er fährt mit dem Rad zur Arbeit.',
  'Die Katze sitzt auf dem Sofa.',
  'Am Himmel ziehen Wolken vorbei.',
  'Ich schreibe einen kurzen Brief.',
  'Die Kinder spielen draußen.',
  'Der Zug kommt pünktlich an.',
  'Wir backen einen Kuchen.',
  'Das Licht ist hell und warm.',
  'Morgen fahren wir ans Meer.',
  'Ich tippe ruhig und genau.',
  'Übung macht den Meister.',
  'Der Regen hört bald auf.',
  'Die Blumen blühen im Frühling.',
  'Wir wandern durch den Wald.',
  'Mein Bruder spielt Gitarre.',
  'Das Essen schmeckt sehr gut.',
  'Die Straße ist heute ruhig.',
  'Ein Vogel singt im Baum.',
  'Wir treffen uns am Bahnhof.',
  'Der Tee ist noch zu heiß.',
  'Sie malt ein buntes Bild.',
  'Im Winter fällt oft Schnee.',
  'Die Uhr zeigt halb acht.',
  'Er hört gern leise Musik.',
  'Wir sitzen zusammen am Tisch.',
  'Das Buch liegt auf dem Regal.',
  'Die Luft ist frisch und klar.',
  'Ich freue mich auf das Wochenende.',
  'Die Tastatur liegt vor mir.',
];

/** Fragen und Sätze mit Komma (Modul 7). */
export const QUESTION_SENTENCES: readonly string[] = [
  'Wie geht es dir?',
  'Hast du heute Zeit?',
  'Wo ist mein Schlüssel?',
  'Wann beginnt der Film?',
  'Kommst du morgen mit?',
  'Was machst du am Wochenende?',
  'Wie spät ist es?',
  'Möchtest du einen Tee?',
  'Hast du die Tasten gefunden?',
  'Wer hat den Kuchen gebacken?',
  'Warum ist der Himmel blau?',
  'Kannst du mir kurz helfen?',
  'Wohin fährst du im Sommer?',
  'Welches Buch liest du gerade?',
  'Gehen wir heute spazieren?',
  'Ist das Fenster noch offen?',
  'Wenn es regnet, bleiben wir zu Hause.',
  'Ich glaube, dass du es schaffst.',
  'Zuerst kommt die Genauigkeit, dann das Tempo.',
  'Am Morgen trinke ich Kaffee, am Abend Tee.',
  'Er lacht, weil der Witz gut ist.',
  'Wir gehen spazieren, obwohl es kalt ist.',
  'Weißt du, wann der Zug fährt?',
  'Ja, ich komme gleich.',
  'Nein, heute habe ich keine Zeit.',
  'Kannst du mir sagen, wo der Bahnhof ist?',
  'Wenn du Zeit hast, ruf mich an.',
  'Sie fragt, ob wir morgen kommen.',
];

/** Längere Sätze mit mehreren Satzteilen (Modul 7). */
export const LONG_SENTENCES: readonly string[] = [
  'Wer jeden Tag ein paar Minuten übt, schreibt bald ohne Hinsehen.',
  'Die Zeigefinger ruhen auf F und J, die Daumen auf der Leertaste.',
  'Nach dem Frühstück gehen wir mit dem Hund eine große Runde spazieren.',
  'Im Sommer sitzen wir gern am See und schauen den Segelbooten zu.',
  'Eine gute Haltung hilft dir, länger konzentriert zu bleiben.',
  'Mein Bruder kocht heute eine Suppe mit frischem Gemüse aus dem Garten.',
  'Langsam und genau zu tippen ist am Anfang wichtiger als schnell zu sein.',
  'Der Zug nach Hamburg fährt in zehn Minuten von Gleis drei ab.',
  'Am Wochenende besuchen wir unsere Großeltern auf dem Land.',
  'Die Bibliothek ist ruhig, und viele Menschen lesen oder lernen dort.',
  'Wenn die Sonne untergeht, färbt sich der Himmel orange und rot.',
  'Ich habe mir vorgenommen, jeden Abend eine kurze Übung zu machen.',
  'Auf dem Markt gibt es frisches Obst, Gemüse und duftendes Brot.',
  'Die Kinder bauen am Strand eine riesige Sandburg mit vielen Türmen.',
  'Nach einem langen Tag tut ein ruhiger Spaziergang besonders gut.',
  'Mit etwas Geduld wird aus jeder neuen Bewegung eine Gewohnheit.',
  'Im Herbst sammeln wir bunte Blätter und trocknen sie zwischen Büchern.',
  'Der Bäcker an der Ecke öffnet schon früh am Morgen seine Tür.',
  'Wer Fehler macht, lernt dazu und wird mit jeder Runde sicherer.',
  'Unsere Nachbarin gießt im Sommer jeden Abend die Blumen im Hof.',
  'Die Straßenbahn fährt alle zehn Minuten vom Bahnhof in die Altstadt.',
  'Beim Tippen bleiben die Hände locker und die Schultern entspannt.',
  'Morgen früh fahren wir mit dem Fahrrad zum See und gehen schwimmen.',
  'Wer blind tippt, kann sich ganz auf den Inhalt seines Textes konzentrieren.',
];

/** Anspruchsvolle Sätze mit vielen Großbuchstaben, Umlauten und Satzzeichen (Modul 9). */
export const PRECISE_SENTENCES: readonly string[] = [
  'Äpfel, Birnen und Pflaumen liegen in der großen Schüssel.',
  'Über Nacht hat es geschneit, und die Straßen sind weiß.',
  'Jörg und Özlem treffen sich um halb zehn am Südbahnhof.',
  'Die Bücherei öffnet montags, mittwochs und freitags.',
  'Können Sie mir bitte sagen, wo die Haltestelle ist?',
  'Fünf Füchse schleichen leise über die frostige Wiese.',
  'Der Schlüssel liegt nicht im Flur, sondern in der Küche.',
  'Größere Übungen erfordern Geduld, Ruhe und Konzentration.',
  'Zwölf Boxkämpfer jagen Viktor quer über den großen Sylter Deich.',
  'Falsches Üben von Xylophonmusik quält jeden größeren Zwerg.',
  'Ärgerlich, dass die Tür schon wieder klemmt.',
  'Heute Abend kocht Lea Spätzle mit Käse und Röstzwiebeln.',
  'Im Frühjahr blühen Tulpen, Narzissen und Krokusse.',
  'Wer übt, gewinnt an Sicherheit, Tempo und Selbstvertrauen.',
  'Übrigens, das Treffen beginnt erst um Viertel nach zwei.',
  'Die Qualität eines Textes zeigt sich oft im Detail.',
  'Jede Übung bringt dich deinem Ziel ein Stück näher.',
  'Bitte prüfe Groß- und Kleinschreibung besonders sorgfältig.',
];
