/**
 * Wortmaterial für die Übungen. Alle Wörter in aktueller deutscher Rechtschreibung.
 * Der Generator filtert automatisch nach den bereits gelernten Zeichen.
 */

/** Einfache erste Wörter (Modul 4). Nomen sind hier bewusst kleingeschrieben, weil die Umschalttaste noch nicht gelernt ist. */
export const FIRST_WORDS: readonly string[] = [
  'da',
  'ja',
  'du',
  'er',
  'es',
  'wo',
  'so',
  'zu',
  'um',
  'im',
  'am',
  'an',
  'in',
  'ob',
  'ab',
  'das',
  'ist',
  'und',
  'wir',
  'ich',
  'sie',
  'ihr',
  'der',
  'die',
  'den',
  'ein',
  'mit',
  'auf',
  'aus',
  'bei',
  'vor',
  'gut',
  'neu',
  'alt',
  'rot',
  'tag',
  'see',
  'weg',
  'tor',
  'hut',
  'ohr',
  'arm',
  'bus',
  'zug',
  'rad',
  'eis',
  'tee',
  'oma',
  'opa',
  'nun',
  'nie',
  'oft',
  'wie',
  'was',
  'wer',
  'hier',
  'dort',
  'auch',
  'noch',
  'doch',
  'aber',
  'oder',
  'wenn',
  'dann',
  'denn',
  'also',
  'mein',
  'dein',
  'sein',
  'kein',
  'eins',
  'zwei',
  'drei',
  'vier',
  'mama',
  'papa',
  'auto',
  'haus',
  'baum',
  'hand',
  'kind',
  'hund',
  'buch',
  'ball',
  'nest',
  'wald',
  'feld',
  'berg',
  'brot',
  'sofa',
  'blau',
  'gelb',
  'grün',
  'rosa',
  'lila',
  'kalt',
  'warm',
  'hell',
  'laut',
  'nett',
  'toll',
  'lieb',
  'klar',
  'frei',
  'voll',
  'viel',
  'hallo',
  'tastatur',
  'finger',
  'taste',
  'sonne',
  'mond',
  'stern',
  'wasser',
  'katze',
  'maus',
  'tisch',
  'stuhl',
  'lampe',
  'fenster',
  'garten',
  'blume',
  'apfel',
  'birne',
  'kuchen',
  'kaffee',
  'milch',
  'schule',
  'freund',
  'familie',
  'spiel',
  'musik',
  'farbe',
  'wolke',
  'regen',
  'winter',
  'sommer',
  'morgen',
  'abend',
  'danke',
  'bitte',
  'gerne',
  'heute',
  'immer',
  'wieder',
  'schnell',
  'langsam',
  'leise',
  'lachen',
  'malen',
  'singen',
  'tanzen',
  'lesen',
  'tippen',
  'lernen',
  'spielen',
  'laufen',
  'fahren',
  'essen',
  'trinken',
  'schlafen',
  'wohnen',
];

/** Häufige kleingeschriebene Wörter: Funktionswörter, Verben, Adjektive, Adverbien. */
export const COMMON_WORDS: readonly string[] = [
  // Funktionswörter
  'der',
  'die',
  'das',
  'den',
  'dem',
  'des',
  'ein',
  'eine',
  'einen',
  'einem',
  'einer',
  'und',
  'oder',
  'aber',
  'doch',
  'denn',
  'weil',
  'dass',
  'wenn',
  'als',
  'wie',
  'ob',
  'so',
  'auch',
  'noch',
  'schon',
  'nur',
  'sehr',
  'mehr',
  'viel',
  'viele',
  'wenig',
  'ganz',
  'gar',
  'nie',
  'oft',
  'immer',
  'wieder',
  'hier',
  'da',
  'dort',
  'jetzt',
  'heute',
  'morgen',
  'gestern',
  'bald',
  'dann',
  'danach',
  'sofort',
  'gern',
  'gerne',
  'ja',
  'nein',
  'nicht',
  'kein',
  'keine',
  'ich',
  'du',
  'er',
  'sie',
  'es',
  'wir',
  'ihr',
  'mich',
  'dich',
  'sich',
  'uns',
  'euch',
  'mir',
  'dir',
  'ihm',
  'ihn',
  'ihnen',
  'mein',
  'dein',
  'sein',
  'unser',
  'euer',
  'mit',
  'ohne',
  'für',
  'gegen',
  'um',
  'aus',
  'bei',
  'nach',
  'von',
  'vor',
  'zu',
  'zur',
  'zum',
  'im',
  'am',
  'an',
  'auf',
  'in',
  'über',
  'unter',
  'neben',
  'zwischen',
  'durch',
  'bis',
  'seit',
  'während',
  'alle',
  'alles',
  'etwas',
  'nichts',
  'man',
  'jeder',
  'jede',
  'jedes',
  'dieser',
  'diese',
  'dieses',
  'wer',
  'was',
  'wo',
  'wann',
  'warum',
  'woher',
  'wohin',
  'welche',
  'hallo',
  'danke',
  'bitte',
  'also',
  'eben',
  'etwa',
  'fast',
  'genau',
  'gleich',
  'kaum',
  'lieber',
  'leider',
  'mal',
  'vielleicht',
  'wirklich',
  'zusammen',
  'allein',
  'oben',
  'unten',
  'links',
  'rechts',
  'vorne',
  'hinten',
  'aha',
  'haha',
  'jaja',
  'als',
  'all',
  'fall',
  'falls',
  'lass',
  'las',
  // Verben
  'sein',
  'haben',
  'werden',
  'machen',
  'gehen',
  'kommen',
  'sehen',
  'geben',
  'nehmen',
  'finden',
  'denken',
  'wissen',
  'sagen',
  'sprechen',
  'lesen',
  'schreiben',
  'tippen',
  'lernen',
  'üben',
  'spielen',
  'arbeiten',
  'laufen',
  'fahren',
  'fliegen',
  'schwimmen',
  'essen',
  'trinken',
  'schlafen',
  'wohnen',
  'leben',
  'lieben',
  'hören',
  'fragen',
  'antworten',
  'helfen',
  'zeigen',
  'bringen',
  'holen',
  'kaufen',
  'kochen',
  'backen',
  'malen',
  'singen',
  'tanzen',
  'lachen',
  'warten',
  'suchen',
  'öffnen',
  'beginnen',
  'bleiben',
  'stehen',
  'liegen',
  'sitzen',
  'legen',
  'stellen',
  'halten',
  'ziehen',
  'drücken',
  'fallen',
  'steigen',
  'wachsen',
  'bauen',
  'planen',
  'reisen',
  'wandern',
  'rufen',
  'glauben',
  'hoffen',
  'freuen',
  'träumen',
  'merken',
  'vergessen',
  'erklären',
  'verstehen',
  'versuchen',
  'gewinnen',
  'teilen',
  'tragen',
  'waschen',
  'putzen',
  'zählen',
  'rechnen',
  'prüfen',
  'testen',
  'ändern',
  'speichern',
  'starten',
  'ist',
  'sind',
  'bin',
  'bist',
  'war',
  'waren',
  'hat',
  'habe',
  'hast',
  'hatte',
  'wird',
  'kann',
  'muss',
  'soll',
  'will',
  'darf',
  'mag',
  'macht',
  'geht',
  'kommt',
  'sieht',
  'gibt',
  'nimmt',
  'findet',
  'denkt',
  'sagt',
  'liest',
  'schreibt',
  'tippt',
  'lernt',
  'spielt',
  'läuft',
  'fährt',
  'isst',
  'trinkt',
  'schläft',
  'wohnt',
  'hört',
  'fragt',
  'hilft',
  'zeigt',
  'sag',
  'lag',
  // Adjektive
  'gut',
  'besser',
  'schlecht',
  'klein',
  'lang',
  'kurz',
  'hoch',
  'tief',
  'alt',
  'neu',
  'jung',
  'schnell',
  'langsam',
  'leicht',
  'schwer',
  'warm',
  'kalt',
  'hell',
  'dunkel',
  'laut',
  'leise',
  'klar',
  'ruhig',
  'still',
  'schön',
  'nett',
  'lieb',
  'froh',
  'glücklich',
  'müde',
  'wach',
  'stark',
  'sanft',
  'weich',
  'hart',
  'nass',
  'trocken',
  'frisch',
  'sauber',
  'voll',
  'leer',
  'offen',
  'frei',
  'fertig',
  'richtig',
  'falsch',
  'sicher',
  'einfach',
  'wichtig',
  'bereit',
  'möglich',
  'nah',
  'weit',
  'rund',
  'gerade',
  'spät',
  'früh',
  'rot',
  'blau',
  'grün',
  'gelb',
  'schwarz',
  'grau',
  'braun',
  'bunt',
  'sauer',
  'lecker',
  'toll',
  'super',
  'prima',
  'klug',
  'wild',
  'mild',
  'fein',
  'echt',
  'locker',
  'entspannt',
  'flüssig',
  'zügig',
  'gemütlich',
  'freundlich',
  'fröhlich',
  'ehrlich',
  'mutig',
  'fleißig',
  'geduldig',
  'kahl',
  'fad',
];

/** Nomen mit Artikel. Großschreibung erst ab der Lektion „Großbuchstaben“. */
export const NOUNS: readonly (readonly [article: string, noun: string])[] = [
  ['das', 'Haus'],
  ['der', 'Baum'],
  ['der', 'Tisch'],
  ['der', 'Stuhl'],
  ['das', 'Buch'],
  ['die', 'Hand'],
  ['der', 'Finger'],
  ['die', 'Taste'],
  ['die', 'Tastatur'],
  ['der', 'Bildschirm'],
  ['die', 'Maus'],
  ['der', 'Computer'],
  ['das', 'Fenster'],
  ['die', 'Tür'],
  ['die', 'Wand'],
  ['der', 'Boden'],
  ['das', 'Dach'],
  ['der', 'Garten'],
  ['die', 'Blume'],
  ['der', 'Wald'],
  ['die', 'Wiese'],
  ['das', 'Feld'],
  ['der', 'Berg'],
  ['das', 'Tal'],
  ['der', 'See'],
  ['das', 'Meer'],
  ['der', 'Fluss'],
  ['der', 'Strand'],
  ['die', 'Insel'],
  ['die', 'Stadt'],
  ['das', 'Dorf'],
  ['der', 'Weg'],
  ['der', 'Platz'],
  ['der', 'Park'],
  ['die', 'Brücke'],
  ['die', 'Bahn'],
  ['der', 'Zug'],
  ['das', 'Auto'],
  ['das', 'Rad'],
  ['der', 'Bus'],
  ['das', 'Schiff'],
  ['das', 'Flugzeug'],
  ['die', 'Mama'],
  ['der', 'Papa'],
  ['das', 'Kind'],
  ['die', 'Mutter'],
  ['der', 'Vater'],
  ['der', 'Bruder'],
  ['die', 'Schwester'],
  ['die', 'Oma'],
  ['der', 'Opa'],
  ['der', 'Freund'],
  ['die', 'Freundin'],
  ['die', 'Familie'],
  ['der', 'Mensch'],
  ['der', 'Hund'],
  ['die', 'Katze'],
  ['der', 'Vogel'],
  ['der', 'Fisch'],
  ['das', 'Pferd'],
  ['die', 'Kuh'],
  ['der', 'Tag'],
  ['die', 'Nacht'],
  ['der', 'Morgen'],
  ['der', 'Abend'],
  ['die', 'Woche'],
  ['der', 'Monat'],
  ['das', 'Jahr'],
  ['die', 'Zeit'],
  ['die', 'Stunde'],
  ['die', 'Minute'],
  ['die', 'Uhr'],
  ['die', 'Sonne'],
  ['der', 'Mond'],
  ['der', 'Stern'],
  ['der', 'Himmel'],
  ['die', 'Wolke'],
  ['der', 'Regen'],
  ['der', 'Schnee'],
  ['der', 'Wind'],
  ['das', 'Wetter'],
  ['das', 'Wasser'],
  ['das', 'Feuer'],
  ['die', 'Luft'],
  ['die', 'Erde'],
  ['das', 'Brot'],
  ['die', 'Butter'],
  ['der', 'Käse'],
  ['der', 'Apfel'],
  ['die', 'Birne'],
  ['der', 'Kaffee'],
  ['der', 'Tee'],
  ['die', 'Milch'],
  ['der', 'Saft'],
  ['die', 'Suppe'],
  ['der', 'Kuchen'],
  ['die', 'Schule'],
  ['die', 'Klasse'],
  ['der', 'Lehrer'],
  ['die', 'Lehrerin'],
  ['die', 'Arbeit'],
  ['das', 'Büro'],
  ['die', 'Pause'],
  ['der', 'Urlaub'],
  ['die', 'Reise'],
  ['der', 'Sport'],
  ['die', 'Musik'],
  ['das', 'Lied'],
  ['der', 'Film'],
  ['das', 'Bild'],
  ['das', 'Spiel'],
  ['der', 'Ball'],
  ['die', 'Farbe'],
  ['der', 'Brief'],
  ['die', 'Karte'],
  ['das', 'Papier'],
  ['der', 'Stift'],
  ['das', 'Heft'],
  ['die', 'Seite'],
  ['das', 'Wort'],
  ['der', 'Satz'],
  ['der', 'Text'],
  ['die', 'Zeile'],
  ['das', 'Zeichen'],
  ['die', 'Frage'],
  ['die', 'Antwort'],
  ['die', 'Idee'],
  ['der', 'Plan'],
  ['das', 'Ziel'],
  ['der', 'Erfolg'],
  ['der', 'Fehler'],
  ['die', 'Übung'],
  ['die', 'Lektion'],
  ['das', 'Training'],
  ['das', 'Tempo'],
  ['der', 'Rhythmus'],
  ['die', 'Geduld'],
  ['die', 'Ruhe'],
  ['die', 'Freude'],
  ['das', 'Glück'],
  ['die', 'Hilfe'],
  ['der', 'Name'],
  ['die', 'Nummer'],
  ['das', 'Telefon'],
  ['die', 'Nachricht'],
  ['der', 'Kalender'],
  ['der', 'Termin'],
  ['die', 'Küche'],
  ['das', 'Zimmer'],
  ['das', 'Bett'],
  ['das', 'Sofa'],
  ['die', 'Lampe'],
  ['das', 'Licht'],
  ['der', 'Schrank'],
  ['der', 'Spiegel'],
  ['der', 'Kopf'],
  ['das', 'Auge'],
  ['das', 'Ohr'],
  ['die', 'Nase'],
  ['der', 'Mund'],
  ['der', 'Arm'],
  ['das', 'Bein'],
  ['der', 'Rücken'],
  ['die', 'Schulter'],
  ['das', 'Herz'],
  ['das', 'Gesicht'],
  ['das', 'Geschenk'],
  ['das', 'Fest'],
  ['der', 'Frühling'],
  ['der', 'Sommer'],
  ['der', 'Herbst'],
  ['der', 'Winter'],
  ['der', 'Montag'],
  ['der', 'Dienstag'],
  ['der', 'Mittwoch'],
  ['der', 'Donnerstag'],
  ['der', 'Freitag'],
  ['der', 'Samstag'],
  ['der', 'Sonntag'],
  ['das', 'Glas'],
  ['das', 'Gas'],
  ['der', 'Hals'],
  ['der', 'Saal'],
  ['der', 'Aal'],
  ['die', 'Salsa'],
  ['die', 'Skala'],
  ['das', 'Öl'],
  ['der', 'Kalk'],
  ['die', 'Saga'],
];

/** Lange und zusammengesetzte Wörter in natürlicher Schreibweise. */
export const LONG_WORDS: readonly string[] = [
  'Tastatur',
  'Bildschirm',
  'Computer',
  'Geburtstag',
  'Schreibtisch',
  'Fingerspitzen',
  'Grundstellung',
  'Leertaste',
  'Umschalttaste',
  'Wochenende',
  'Sonnenschein',
  'Frühstück',
  'Mittagessen',
  'Abendessen',
  'Kaffeetasse',
  'Haustür',
  'Fahrrad',
  'Zeitung',
  'Wohnzimmer',
  'Schlafzimmer',
  'Badezimmer',
  'Kinderzimmer',
  'Spielplatz',
  'Bahnhof',
  'Flughafen',
  'Krankenhaus',
  'Supermarkt',
  'Bäckerei',
  'Bibliothek',
  'Universität',
  'Schmetterling',
  'Regenbogen',
  'Sommerferien',
  'Winterjacke',
  'Handschuh',
  'Taschenlampe',
  'Kühlschrank',
  'Waschmaschine',
  'Fernseher',
  'Lautsprecher',
  'Kopfhörer',
  'Geschwindigkeit',
  'Genauigkeit',
  'Konzentration',
  'Übungszeit',
  'Lernfortschritt',
  'Erfahrung',
  'Gelegenheit',
  'Entscheidung',
  'Möglichkeit',
  'Verantwortung',
  'Zusammenarbeit',
  'Freundschaft',
  'Gesundheit',
  'Wissenschaft',
  'Geschichte',
  'Mathematik',
  'Erdkunde',
  'Hausaufgaben',
  'Klassenzimmer',
  'Nachbarschaft',
  'Schokolade',
  'Erdbeere',
  'Himbeere',
  'Blaubeere',
  'Apfelkuchen',
  'Tomatensuppe',
  'Gemüsesuppe',
  'Spaziergang',
  'Ausflug',
  'Abenteuer',
  'Gewitter',
  'Sonnenuntergang',
  'Sternenhimmel',
  'Mondlicht',
  'Wanderweg',
  'Bergsee',
  'Leuchtturm',
  'Segelboot',
  'Strandkorb',
  'Sandburg',
  'Muschel',
  'Eichhörnchen',
  'Kaninchen',
  'Meerschweinchen',
  'Wellensittich',
  'Goldfisch',
  'Schildkröte',
  'Briefkasten',
  'Postkarte',
  'Wörterbuch',
  'Notizbuch',
  'Bleistift',
  'Radiergummi',
  'Taschenrechner',
  'Stundenplan',
  'Pausenhof',
  'Turnhalle',
  'Kindergarten',
  'Feuerwehr',
  'Polizei',
  'Rathaus',
  'Marktplatz',
  'Straßenbahn',
  'Autobahn',
  'Tankstelle',
  'Parkplatz',
  'Ampel',
  'Zebrastreifen',
  'wunderbar',
  'ausgezeichnet',
  'gleichmäßig',
  'regelmäßig',
  'aufmerksam',
  'zuverlässig',
  'ausdauernd',
  'konzentriert',
  'entspannt',
  'fantastisch',
  'großartig',
  'hervorragend',
  'vollständig',
  'verständlich',
  'schrittweise',
  'erstaunlich',
  'gemeinsam',
  'freundlich',
  'hilfsbereit',
  'pünktlich',
  'gründlich',
  'vorsichtig',
  'sorgfältig',
  'selbstbewusst',
];

/** Wörter mit ß (Lektion „ß“). */
export const ESZETT_WORDS: readonly string[] = [
  'groß',
  'weiß',
  'heiß',
  'süß',
  'Fuß',
  'Gruß',
  'Spaß',
  'Straße',
  'heißen',
  'draußen',
  'gießen',
  'schließen',
  'außen',
  'bloß',
  'Maß',
  'Soße',
  'Größe',
  'grüßen',
  'beißen',
  'fließen',
  'Strauß',
  'Fußball',
  'Grüße',
  'Weißbrot',
  'Großstadt',
  'Außenseite',
  'gemäß',
  'Fleiß',
  'fleißig',
  'Kloß',
  'Floß',
  'Spieß',
  'Schoß',
  'Gießkanne',
  'Fußweg',
  'Großeltern',
  'weißt',
  'heißt',
  'süßer',
  'größer',
  'genießen',
  'stoßen',
  'Stoß',
  'Maßband',
  'Spaßvogel',
  'Ruß',
  'Blumenstrauß',
  'Grußkarte',
  'Hauptstraße',
  'Sträußchen',
  'Fußspur',
];

/** Verwechslungsgefahr: Wortpaare, die sich nur minimal unterscheiden (Modul Genauigkeit). */
export const CONFUSABLE_PAIRS: readonly (readonly [string, string])[] = [
  ['das', 'dass'],
  ['seid', 'seit'],
  ['wieder', 'wider'],
  ['Stadt', 'statt'],
  ['Lied', 'Lid'],
  ['malen', 'mahlen'],
  ['Rad', 'Rat'],
  ['war', 'wahr'],
  ['Tod', 'tot'],
  ['Seite', 'Saite'],
  ['Wal', 'Wahl'],
  ['Mine', 'Miene'],
  ['viel', 'fiel'],
  ['Lehre', 'Leere'],
  ['Bote', 'Boote'],
  ['Ofen', 'offen'],
  ['Hüte', 'Hütte'],
  ['Schal', 'Schall'],
  ['kam', 'Kamm'],
  ['Bett', 'Beet'],
  ['Staat', 'Stadt'],
  ['Mal', 'Mahl'],
  ['fast', 'fasst'],
  ['Masse', 'Maße'],
  ['Mus', 'muss'],
  ['bis', 'Biss'],
  ['Weise', 'Waise'],
  ['Lerche', 'Lärche'],
  ['Feld', 'fällt'],
  ['Held', 'hält'],
  ['Ende', 'Ente'],
  ['Kiste', 'Küste'],
  ['Tier', 'Tür'],
  ['lesen', 'lösen'],
  ['Bären', 'Beeren'],
  ['Hasen', 'Hosen'],
  ['Wagen', 'wagen'],
  ['Essen', 'essen'],
  ['Laden', 'laden'],
];

/** Kurze Wendungen mit Komma, Punkt und Bindestrich – noch ohne Großbuchstaben. */
export const PUNCTUATION_PHRASES: readonly string[] = [
  'ja, gern.',
  'nein, danke.',
  'gut, dann los.',
  'bis bald.',
  'na klar.',
  'so, fertig.',
  'eins, zwei, drei.',
  'rot, gelb, grün.',
  'links, rechts, links.',
  'heute, morgen, immer.',
  'ost-west',
  'nord-süd',
  'e-mail',
  'u-bahn',
  's-bahn',
  't-shirt',
  'blau-grün',
  'hallo, schön dich zu sehen.',
  'tee oder kaffee.',
  'hier, bitte.',
  'danke, gleichfalls.',
  'erst lesen, dann tippen.',
  'ruhig, genau, sauber.',
  'ja, das passt.',
  'gut gemacht.',
  'morgen, nicht heute.',
  'auf, zu, auf.',
  'oben, unten, mitte.',
  'schritt für schritt.',
  'mit der u-bahn zur arbeit.',
  'eine e-mail schreiben.',
  'nord-süd und ost-west.',
];
