/* AUTOMATISCH ERZEUGT – nicht von Hand bearbeiten.
 * Quelle: src/content/lessons/**, Reihenfolge: src/content/order.ts
 * Neu erzeugen mit: npm run gen:meta
 */
import type { LessonMeta } from './types'

export const LESSON_META: LessonMeta[] = [
  {
    slug: "was-ist-claude",
    track: "basics",
    title: "Was ist Claude?",
    description: "Claude ist ein KI-Assistent, mit dem du in normaler Sprache sprichst. Hier erfährst du in fünf Minuten, was das genau bedeutet.",
    minutes: 6,
    keywords: ["ki","assistent","anthropic","sprachmodell","llm","einstieg","start"],
  },
  {
    slug: "claude-vs-suchmaschine",
    track: "basics",
    title: "Claude vs. Suchmaschine",
    description: "Google findet Seiten. Claude erledigt Aufgaben. Wann du was benutzt – und warum der Unterschied deine Ergebnisse verändert.",
    minutes: 5,
    keywords: ["google","suche","unterschied","recherche","quellen","vergleich"],
  },
  {
    slug: "was-kann-claude",
    track: "basics",
    title: "Was kann Claude?",
    description: "Ein realistischer Überblick über die Stärken von Claude – mit sofort nutzbaren Beispielen für Büro, Schule, Beruf und Code.",
    minutes: 7,
    keywords: ["fähigkeiten","stärken","anwendungsfälle","überblick","use cases"],
  },
  {
    slug: "was-kann-claude-nicht",
    track: "basics",
    title: "Was kann Claude nicht?",
    description: "Grenzen ehrlich erklärt: Halluzinationen, fehlende Aktualität, Rechnen, Gedächtnis. Und wie du dich dagegen absicherst.",
    minutes: 7,
    keywords: ["grenzen","halluzination","fehler","risiken","stichtag","gedächtnis","sicherheit"],
  },
  {
    slug: "erster-prompt",
    track: "basics",
    title: "Wie schreibe ich meinen ersten Prompt?",
    description: "Die einfachste Prompt-Formel für Anfänger: Aufgabe + Kontext + Format. In drei Minuten anwendbar.",
    minutes: 6,
    keywords: ["prompt","schreiben","formel","anfang","erste schritte","aufgabe"],
  },
  {
    slug: "bessere-antworten",
    track: "basics",
    title: "Wie bekomme ich bessere Antworten?",
    description: "Fünf Stellschrauben, die sofort wirken – und die Erkenntnis, dass das Gespräch wichtiger ist als der perfekte erste Prompt.",
    minutes: 6,
    keywords: ["qualität","nachfragen","iteration","verbessern","antwort","feedback"],
  },
  {
    slug: "wo-nutze-ich-claude",
    track: "basics",
    title: "Wo benutze ich Claude?",
    description: "Chat, Desktop, Handy, Claude Code, API: Welche Oberfläche wofür gedacht ist – und womit du als Anfänger startest.",
    minutes: 5,
    keywords: ["app","oberfläche","web","desktop","api","claude code","plattform","wo"],
  },
  {
    slug: "sicher-starten",
    track: "basics",
    title: "Sicher starten: Daten, Prüfen, Verantwortung",
    description: "Welche Daten du besser nicht hineinkopierst, wie du Ergebnisse prüfst und wo deine Verantwortung beginnt.",
    minutes: 6,
    keywords: ["datenschutz","sicherheit","vertraulich","dsgvo","prüfen","verantwortung","risiko"],
  },
  {
    slug: "gute-prompts",
    track: "prompting",
    title: "Gute Prompts schreiben",
    description: "Die erweiterte Prompt-Struktur mit sechs Bausteinen – und wann du welche davon wirklich brauchst.",
    minutes: 8,
    keywords: ["prompt engineering","struktur","bausteine","aufbau","vorlage"],
  },
  {
    slug: "kontext-geben",
    track: "prompting",
    title: "Kontext geben",
    description: "Kontext ist der Unterschied zwischen einer generischen und einer brauchbaren Antwort. Was genau hineingehört – und was nicht.",
    minutes: 7,
    keywords: ["kontext","hintergrund","informationen","situation","details"],
  },
  {
    slug: "rollen-und-aufgaben",
    track: "prompting",
    title: "Rollen und Aufgaben",
    description: "Wie eine Rolle den Blickwinkel verändert – und warum eine klare Aufgabe wichtiger ist als jede Rolle.",
    minutes: 6,
    keywords: ["rolle","persona","perspektive","experte","aufgabe","verb"],
  },
  {
    slug: "beispiele-geben",
    track: "prompting",
    title: "Beispiele geben",
    description: "Ein einziges gutes Beispiel wirkt oft stärker als zehn Sätze Erklärung. Wie du deinen Stil übertragbar machst.",
    minutes: 6,
    keywords: ["beispiel","few shot","muster","stil","vorlage","ton treffen"],
  },
  {
    slug: "ergebnisse-strukturieren",
    track: "prompting",
    title: "Ergebnisse strukturieren",
    description: "Tabelle, Liste, Fließtext oder Vorlage? Wie du das Ausgabeformat festlegst und damit Nacharbeit sparst.",
    minutes: 6,
    keywords: ["format","tabelle","liste","struktur","ausgabe","vorlage","json"],
  },
  {
    slug: "prompts-verbessern",
    track: "prompting",
    title: "Prompts verbessern",
    description: "Ein festes Verfahren, mit dem du jeden schwachen Prompt in drei Schritten verbesserst – plus der interaktive Prompt-Verbesserer dieser Academy.",
    minutes: 7,
    keywords: ["verbessern","optimieren","überarbeiten","schwach","stark","prompt verbesserer"],
  },
  {
    slug: "fehler-korrigieren",
    track: "prompting",
    title: "Fehler korrigieren",
    description: "Was tun, wenn die Antwort falsch, erfunden oder am Thema vorbei ist? Fünf typische Fehlerbilder und ihre Gegenmittel.",
    minutes: 7,
    keywords: ["fehler","falsch","korrigieren","halluzination","abweichung","diskussion"],
  },
  {
    slug: "folgefragen-stellen",
    track: "prompting",
    title: "Folgefragen stellen",
    description: "Das Gespräch ist das eigentliche Werkzeug. Sechs Folgefragen, die aus einer okayen Antwort ein gutes Ergebnis machen.",
    minutes: 6,
    keywords: ["nachfragen","dialog","gespräch","vertiefen","iteration","folgefrage"],
  },
  {
    slug: "texte-erstellen",
    track: "work",
    title: "Texte erstellen",
    description: "E-Mails, Angebote, Aushänge, Social-Posts: Wie du in wenigen Minuten zu einem Text kommst, der wirklich nach dir klingt.",
    minutes: 7,
    keywords: ["schreiben","e-mail","text","formulieren","entwurf","stil"],
  },
  {
    slug: "texte-analysieren",
    track: "work",
    title: "Texte analysieren",
    description: "Verträge, Konzepte, Angebote, Feedback: Wie du aus einem Text genau das herausholst, was du wissen musst.",
    minutes: 7,
    keywords: ["analyse","vertrag","prüfen","bewerten","lücken","risiken","feedback"],
  },
  {
    slug: "dateien-verstehen",
    track: "files",
    title: "Dateien verstehen (PDF, Bild, Text)",
    description: "Dateien hochladen und gezielt auswerten: PDFs, Fotos, Screenshots, Textdateien – inklusive der typischen Stolperfallen.",
    minutes: 7,
    keywords: ["pdf","datei","hochladen","bild","foto","screenshot","dokument","ocr"],
  },
  {
    slug: "tabellen-analysieren",
    track: "files",
    title: "Tabellen analysieren",
    description: "Excel und CSV auswerten lassen – und die wichtigste Regel: Claude ist kein Taschenrechner, aber ein sehr guter Analytiker.",
    minutes: 7,
    keywords: ["excel","csv","tabelle","zahlen","auswertung","daten","formel","rechnen"],
  },
  {
    slug: "dokumente-erstellen",
    track: "files",
    title: "Dokumente erstellen",
    description: "Von der Notiz zum fertigen Bericht, Konzept oder Handbuch – mit einer Gliederung, die du vorher freigibst.",
    minutes: 7,
    keywords: ["bericht","konzept","dokument","gliederung","handbuch","protokoll","erstellen"],
  },
  {
    slug: "recherche",
    track: "work",
    title: "Recherche",
    description: "Mit Claude recherchieren, ohne auf erfundene Quellen hereinzufallen – und wann du besser selbst suchst.",
    minutes: 6,
    keywords: ["recherche","quellen","websuche","belege","vergleichen","informationen"],
  },
  {
    slug: "zusammenfassungen",
    track: "work",
    title: "Zusammenfassungen",
    description: "Die häufigste Claude-Aufgabe – und die, bei der die meisten den entscheidenden Zusatz vergessen: wofür du die Zusammenfassung brauchst.",
    minutes: 5,
    keywords: ["zusammenfassen","kürzen","kernaussagen","summary","protokoll"],
  },
  {
    slug: "brainstorming",
    track: "work",
    title: "Brainstorming",
    description: "Ideen sammeln, ohne bei den ersten fünf naheliegenden zu landen – mit Mengenvorgabe, Perspektivwechsel und Bewertung.",
    minutes: 5,
    keywords: ["ideen","kreativ","brainstorming","sammeln","alternativen","varianten"],
  },
  {
    slug: "planung",
    track: "work",
    title: "Planung",
    description: "Aus einem vagen Vorhaben einen Plan machen, der Abhängigkeiten, Risiken und Verantwortlichkeiten enthält.",
    minutes: 6,
    keywords: ["plan","projekt","zeitplan","meilenstein","aufgaben","organisieren"],
  },
  {
    slug: "lernen-mit-claude",
    track: "work",
    title: "Lernen mit Claude",
    description: "Claude als geduldiger Lehrer: erklären lassen, abgefragt werden, Verständnislücken finden – ohne sich selbst zu belügen.",
    minutes: 6,
    keywords: ["lernen","erklären","prüfung","abfragen","verstehen","nachhilfe","studium"],
  },
  {
    slug: "projekte-wissenskontext",
    track: "projects",
    title: "Projekte und Wissenskontext",
    description: "Hintergrundwissen einmal hinterlegen statt in jedem Chat neu erklären – so baust du dir einen dauerhaften Arbeitskontext.",
    minutes: 7,
    keywords: ["projekt","wissen","kontext","dauerhaft","vorlage","anweisungen","wissensbasis"],
  },
  {
    slug: "lange-aufgaben",
    track: "projects",
    title: "Längere Aufgaben bewältigen",
    description: "Große Vorhaben in Etappen zerlegen, Zwischenstände sichern und verhindern, dass ein langes Gespräch abdriftet.",
    minutes: 7,
    keywords: ["groß","lang","zerlegen","etappen","übergabe","zwischenstand","abdriften"],
  },
  {
    slug: "komplexe-prompts",
    track: "advanced",
    title: "Komplexe Prompts",
    description: "Mehrstufige Aufträge, Denkschritte, Selbstprüfung und Bedingungen – wenn ein einfacher Prompt nicht mehr reicht.",
    minutes: 8,
    keywords: ["komplex","mehrstufig","denkschritte","bedingungen","selbstprüfung","fortgeschritten"],
  },
  {
    slug: "workflows",
    track: "projects",
    title: "Workflows bauen",
    description: "Wiederkehrende Arbeit in feste Abläufe verwandeln: Prompt-Ketten, Vorlagen und Qualitätsprüfungen.",
    minutes: 7,
    keywords: ["workflow","ablauf","kette","wiederholen","prozess","standard","vorlage"],
  },
  {
    slug: "automatisierung",
    track: "advanced",
    title: "Automatisierung",
    description: "Wann sich Automatisieren lohnt, welche Stufen es gibt – und welche Kontrolle immer beim Menschen bleiben muss.",
    minutes: 7,
    keywords: ["automatisieren","api","skript","batch","stapel","wiederholung","agent"],
  },
  {
    slug: "fehleranalyse",
    track: "advanced",
    title: "Fehleranalyse",
    description: "Systematisch herausfinden, warum ein Ergebnis nicht stimmt – bei Texten, Prozessen und technischen Fehlern.",
    minutes: 7,
    keywords: ["fehler","debugging","ursache","analyse","problem","fehlersuche","systematisch"],
  },
  {
    slug: "grosse-projekte",
    track: "advanced",
    title: "Große Projekte",
    description: "Wenn mehrere Menschen, viele Dokumente und Wochen an Arbeit zusammenkommen: Struktur, Gedächtnis und Qualitätssicherung.",
    minutes: 7,
    keywords: ["projekt","team","groß","koordination","dokumentation","struktur","langfristig"],
  },
  {
    slug: "cc-was-ist-claude-code",
    track: "claude-code",
    title: "Was ist Claude Code?",
    description: "Claude, der nicht nur redet, sondern Dateien auf deinem Computer lesen und ändern kann – erklärt ohne Fachchinesisch.",
    minutes: 6,
    keywords: ["claude code","cli","terminal","dateien","entwickeln","einstieg"],
  },
  {
    slug: "cc-terminal",
    track: "claude-code",
    title: "Was ist ein Terminal?",
    description: "Das schwarze Fenster mit dem Textcursor – erklärt für Menschen, die es noch nie geöffnet haben.",
    minutes: 6,
    keywords: ["terminal","konsole","kommandozeile","shell","eingabeaufforderung","befehle"],
  },
  {
    slug: "cc-ordner-und-dateien",
    track: "claude-code",
    title: "Ordner, Dateien und Pfade",
    description: "Was ein Pfad ist, warum Dateiendungen zählen und welche Ordnerstruktur dir das Leben leichter macht.",
    minutes: 5,
    keywords: ["ordner","datei","pfad","verzeichnis","endung","struktur"],
  },
  {
    slug: "cc-projekt",
    track: "claude-code",
    title: "Was ist ein Projekt? (und was ist Git?)",
    description: "Der Projektordner als Arbeitsbereich – und warum Git die beste Sicherheitsleine für Claude Code ist.",
    minutes: 7,
    keywords: ["projekt","git","versionierung","backup","sicherung","commit","repository"],
  },
  {
    slug: "cc-was-ist-code",
    track: "claude-code",
    title: "Was ist Code?",
    description: "Code für Menschen, die noch nie programmiert haben – und warum du ihn lesen können solltest, auch wenn du ihn nicht schreibst.",
    minutes: 6,
    keywords: ["code","programmieren","programmiersprache","html","skript","anfänger"],
  },
  {
    slug: "cc-starten",
    track: "claude-code",
    title: "Claude Code starten",
    description: "Der erste Start: Was du vorbereitest, was beim ersten Mal passiert und wie du sicher wieder herauskommst.",
    minutes: 6,
    keywords: ["starten","installation","erste schritte","einrichten","öffnen","beenden"],
  },
  {
    slug: "cc-aufgaben-geben",
    track: "claude-code",
    title: "Aufgaben geben",
    description: "Wie du Aufträge in Claude Code formulierst: mit Plan-Zuerst-Regel, klarem Umfang und Abbruchbedingung.",
    minutes: 6,
    keywords: ["aufgabe","auftrag","prompt","plan","umfang","anweisung"],
  },
  {
    slug: "cc-dateien-analysieren",
    track: "claude-code",
    title: "Dateien analysieren lassen",
    description: "Der risikoloseste und unterschätzteste Teil von Claude Code: verstehen, was in einem Projekt eigentlich passiert.",
    minutes: 5,
    keywords: ["analysieren","verstehen","lesen","überblick","projekt verstehen","inventur"],
  },
  {
    slug: "cc-aenderungen",
    track: "claude-code",
    title: "Änderungen durchführen lassen",
    description: "Der Schritt, an dem tatsächlich etwas passiert – mit einem Ablauf, der ihn ungefährlich macht.",
    minutes: 6,
    keywords: ["ändern","bearbeiten","umsetzen","schreiben","zustimmen","genehmigen"],
  },
  {
    slug: "cc-aenderungen-pruefen",
    track: "claude-code",
    title: "Änderungen kontrollieren",
    description: "Wie man einen Diff liest, worauf man achtet – und was man tut, wenn etwas nicht stimmt.",
    minutes: 6,
    keywords: ["prüfen","diff","kontrolle","review","rückgängig","git diff"],
  },
  {
    slug: "cc-fehler-finden",
    track: "claude-code",
    title: "Fehler finden und beheben",
    description: "Wenn etwas nicht funktioniert: Fehlermeldungen lesen, Ursachen eingrenzen und sicher reparieren.",
    minutes: 6,
    keywords: ["fehler","fehlermeldung","debugging","kaputt","reparieren","error"],
  },
  {
    slug: "cc-sicher-arbeiten",
    track: "claude-code",
    title: "Sicher arbeiten mit Claude Code",
    description: "Die wichtigste Lektion dieses Bereichs: Regeln, die verhindern, dass aus einer Hilfe ein Problem wird.",
    minutes: 7,
    keywords: ["sicherheit","risiko","backup","gefährlich","löschen","regeln","schutz"],
  },
  {
    slug: "cc-website-bauen",
    track: "claude-code",
    title: "Eine Website bauen",
    description: "Von der leeren Seite zur funktionierenden Website – Schritt für Schritt, ohne Vorkenntnisse.",
    minutes: 8,
    keywords: ["website","html","css","bauen","seite","erstellen","webseite"],
  },
  {
    slug: "cc-website-testen",
    track: "claude-code",
    title: "Eine Website testen",
    description: "Bevor etwas online geht: die Prüfliste, die alle typischen Fehler findet – auch ohne technisches Wissen.",
    minutes: 6,
    keywords: ["testen","prüfen","mobil","browser","fehler","checkliste","qualität"],
  },
  {
    slug: "cc-deployen",
    track: "claude-code",
    title: "Eine Website veröffentlichen",
    description: "Von deinem Rechner ins Internet: was „Deployment\" bedeutet, welche Wege es gibt und was vorher geprüft sein muss.",
    minutes: 7,
    keywords: ["deploy","veröffentlichen","hosting","online","domain","live","server"],
  },
  {
    slug: "modelle-verstehen",
    track: "advanced",
    title: "Modelle verstehen",
    description: "Opus, Sonnet, Haiku – was die Unterschiede bedeuten, wann sie eine Rolle spielen und wann nicht.",
    minutes: 6,
    keywords: ["modell","opus","sonnet","haiku","auswahl","denkzeit","effort","kosten"],
  },
  {
    slug: "kontextfenster-und-token",
    track: "advanced",
    title: "Kontextfenster und Token",
    description: "Was ein Token ist, wie groß das Kontextfenster ist und welche praktischen Folgen das für deine Arbeit hat.",
    minutes: 6,
    keywords: ["token","kontextfenster","länge","grenze","limit","kosten","speicher"],
  },
  {
    slug: "api-grundlagen",
    track: "advanced",
    title: "API-Grundlagen",
    description: "Claude in eigene Programme einbauen – was eine API ist, wie ein Aufruf aussieht und was du vorher wissen solltest.",
    minutes: 8,
    keywords: ["api","programmieren","entwickler","schnittstelle","integration","sdk","code"],
  },
  {
    slug: "agenten-und-tools",
    track: "advanced",
    title: "Agenten und Werkzeuge",
    description: "Wenn Claude nicht nur antwortet, sondern handelt: Werkzeuge, Agenten und die Frage, wann sich das überhaupt lohnt.",
    minutes: 7,
    keywords: ["agent","tools","werkzeuge","mcp","funktionsaufruf","autonomie"],
  },
  {
    slug: "qualitaet-pruefen",
    track: "advanced",
    title: "Qualität messen statt raten",
    description: "Wie du feststellst, ob eine Änderung wirklich besser ist – mit einem einfachen Testsatz statt mit Bauchgefühl.",
    minutes: 7,
    keywords: ["qualität","messen","test","eval","vergleich","verbessern","bewerten"],
  },
  {
    slug: "sicherheit-profi",
    track: "advanced",
    title: "Sicherheit und Verantwortung",
    description: "Datenschutz, Prompt-Injection, Grenzen der Automatisierung – was du wissen musst, bevor du KI in ernsthafte Abläufe einbaust.",
    minutes: 8,
    keywords: ["sicherheit","datenschutz","prompt injection","risiko","compliance","verantwortung","dsgvo"],
  },
]
